export const shoppingList = [
  {
    id: 1,
    img: "./assets/png/img_digital_camera.jpg",
    name: "레트로 카메라",
    price: 34900,
    category: "digital",
  },
  {
    id: 2,
    img: "./assets/png/img_airpod_max.png",
    name: "에어팟 맥스",
    price: 709000,
    category: "digital",
  },
  {
    id: 3,
    img: "./assets/png/img_speaker.png",
    name: "블루투스 스피커",
    price: 1850000,
    category: "digital",
  },
  {
    id: 4,
    img: "./assets/png/img_iMac.png",
    name: "iMac",
    price: 2290000,
    category: "digital",
  },
  {
    id: 5,
    img: "./assets/png/img_chocolate.png",
    name: "레더라 초콜릿",
    price: 60000,
    category: "food",
  },
  {
    id: 6,
    img: "./assets/png/img_mozzi.png",
    name: "과일모찌",
    price: 23900,
    category: "food",
  },
  {
    id: 7,
    img: "./assets/png/img_rollcake.png",
    name: "롤케이크",
    price: 15900,
    category: "food",
  },
  {
    id: 8,
    img: "./assets/png/img_bodypillow.png",
    name: "오리 바디필로우",
    price: 12900,
    category: "living",
  },
  {
    id: 9,
    img: "./assets/png/img_mood_lamp.png",
    name: "무드등",
    price: 132000,
    category: "living",
  },
  {
    id: 10,
    img: "./assets/png/img_book.png",
    name: "애프터 다크",
    price: 14200,
    category: "living",
  },
];
